#!/bin/bash -e
# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023-2026 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

case x"$1" in
	x      ) echo usage : $0 [-m32] path/to/c-compiler >&2 ; exit 2 ;;
	x-h    ) echo usage : $0 [-m32] path/to/c-compiler >&2 ; exit 2 ;;
	x--help) echo usage : $0 [-m32] path/to/c-compiler >&2 ; exit 2 ;;
	x-m32  ) m32=-m32 ; shift                                       ;;
esac

cc=$1

info=$($cc $m32 -v -o /dev/null -xc - <<< "int main(){}" 2>&1)

case $($cc --version | head -1) in
	*clang*)
		set $info
		while [ $# != 0 ] ; do
			case $1 in
				-L ) libs="$libs $2" ; shift ;;
				-L*) libs="$libs ${1#-L}"    ;;
				*  )                         ;;
			esac
			shift
		done
	;;
	*)
		for libs in $info ; do
			case $libs in
				LIBRARY_PATH=*)                  # e.g. : LIBRARY_PATH=/usr/lib/x:/a/b:/c:/a/b/c/..
					libs="${libs#LIBRARY_PATH=}" # e.g. : /usr/lib/x:/a/b:/c:/a/b/c/..
					libs="${libs//:/ }"          # e.g. : /usr/lib/x /a/b /c /a/b/c/..
					break
				;;
			esac
		done
	;;
esac
libs="$(realpath $libs | sort -u)"               # e.g. : /a/b /c /usr/lib/x

ld_library_path=
for l in $libs ; do # e.g. : /a/b /c (filter out standard dirs as required in case of installed package)
	case $l/ in
		/lib/*       )                                       ;;
		/lib64/*     )                                       ;;
		/lib32/*     )                                       ;;
		/libx32/*    )                                       ;;
		/usr/lib/*   )                                       ;;
		/usr/lib64/* )                                       ;;
		/usr/lib32/* )                                       ;;
		/usr/libx32/*)                                       ;;
		*            ) ld_library_path="$ld_library_path:$l" ;;
	esac
done
ld_library_path=${ld_library_path#:}

echo $ld_library_path
