#!/bin/bash
# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

version=$(
	sed -n -e 's://.*\(\(START\|END\)_OF_VERSIONING\).*:\1:' -e 's://.*::' -e 's:/\*.*\*/::g' -e '/START_OF_VERSIONING/,/END_OF_VERSIONING/p' "$@" \
|	grep -vx '\(START\|END\)_OF_VERSIONING'                                                                                                                    \
|	tr -d ' \t\n'                                                                                                                                                    \
|	md5sum                                                                                                                                                           \
|	cut -d' ' -f1
)
cat <<EOF
constexpr char VersionMrkr[] = "$version" ;
EOF
