#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -done 2 -may_rerun 0 -new 2 -rerun 0 -steady 0 -was_done 0 lmake src2.import
ut_launch -done 2 -may_rerun 0 -new 1 -rerun 0 -steady 0 -was_done 0 lmake src1.import

ut_launch -done 1 -steady 0 lmake src1.import

touch hello.py
ut_launch -done 1 -steady 1 lmake src1.import

echo >>hello.py
ut_launch -done 1 -changed 1 -rerun 0 -steady 2 lmake src1.import
ut_launch -done 1            -rerun 0 -steady 2 lmake src2.import
