#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cat <<"EOF" >>Lmakefile.py

class NewDep(BaseRule) :
	target = 'new_dir/dep{Digit}'
	cmd    = 'echo dep{Digit}'
class ChDir(BaseRule) :
	target = 'chdir{Digit}'
	cmd = multi_strip('''
		cd new_dir
		cat dep{Digit}
	''')

EOF

ut_launch -failed 2 -rc 1 lmake chdir1

echo 'ChDir.auto_mkdir = True' >> Lmakefile.py

ut_launch -may_rerun 1 -done 3 lmake chdir1
