#!/bin/bash -e

# This file is part of the lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

REF=src1+{auto1.hide}.ref
cat src1 > $REF
echo '#auto1' >> $REF
echo $REF >> Manifest
ut_launch -done 5 -may_rerun 1 -new 2 lmake src1+{auto1.hide}.ok
