#!/bin/bash -e

# This file is part of the lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cat <<"EOF" >>Lmakefile.py

class NewDep(BaseRule) :
	target = 'new_dir/dep{Digit}'
	cmd    = 'echo dep$Digit'
class Chdir(BaseRule) :
	target = 'chdir{Digit}'
	cmd = '''
		cd new_dir
		cat dep$Digit
	'''

EOF

ut_launch -failed 1 -rc 1 lmake chdir1

echo 'Chdir.auto_mkdir = True' >> Lmakefile.py

ut_launch -may_rerun 1 -done 2 lmake chdir1
