#!/bin/bash -e

# This file is part of the lmake distribution (https://wgit.doliam.net/cdy/lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

REF=src1+{src2.version}.ref
TARGET=src1+{src2.version}.ok
( cat src1 src2 ; echo '#version1' ) > $REF
echo $REF >>Manifest

ut_launch -done 5 -new 3 lmake $TARGET.cpy

# update source
echo x >> src2
ut_launch -done 3 -failed 1 -new 1 -rc 1 lmake $TARGET.cpy

( cat src1 src2 ; echo '#version1' ) > $REF
ut_launch -done 1 -new 1 -rc 0 -steady 0 lmake $TARGET.cpy

# update rule cmd
echo 'version = 2' >> Lmakefile.py
ut_launch -done 3 -failed 1 -rc 1 lmake $TARGET

( cat src1 src2 ; echo '#version2' ) > $REF
ut_launch -steady 0 -done 1 -new 1 -rc 0 lmake $TARGET

echo 'version = 3' >> Lmakefile.py
ut_launch -done 3 -failed 1 -rc 1 lmake $TARGET

( cat src1 src2 ; echo '#version3' ) > $REF
ut_launch -done 1 -new 1 -rc 0 -steady 0 lmake $TARGET

# update rules
ut_launch -done 0 -rc 1 lmake $TARGET.cpyn

echo 'add_rule()' >> Lmakefile.py
ut_launch -done 1 -rc 0 lmake $TARGET.cpyn
