#!/bin/bash -e

# This file is part of the lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -done 1 -new 1 lmake src1.4.wait &
sleep 1
lmake src1.2.wait &
sleep 1
kill -2 %2
wait %2 || :
ut_launch -done 1 lmake src1.2.wait
wait %1
