#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023-2025 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

TARGET=src1.w6.wait
date +%T.%N >&2
lmake $TARGET &
date +%T.%N >&2
sleep 3
date +%T.%N >&2
kill -2 %1
date +%T.%N >&2
echo 'Wait.stems["Wait"] = "("+Wait.stems["Wait"]+")"' >> Lmakefile.py
wait %1 || :
date +%T.%N >&2
ut_launch -done 1 -steady 2 -manual 0 lmake $TARGET
date +%T.%N >&2
