#!/bin/bash -e

# This file is part of the lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -done 1 -failed 0 -new 1 -timeout 0 -rc 0 lmake src1.4.wait5
ut_launch -done 0 -failed 0 -new 0 -timeout 1 -rc 1 lmake src1.6.wait5
