#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023-2025 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -done 1 -new 1 -changed 1 -dep_error 1 -rc 1 lmake src1.9r.wait &
sleep 7
date +%T.%N ; echo new1 > src1 ; date +%T.%N
wait %1

ut_launch -done 1 -steady 0 -dep_error 0 -rc 0 lmake src1.9r.wait
