#!/bin/bash -e

# This file is part of the lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -done 0 -failed 0 -frozen 0                    -rc 1 -steady 0 lmake src3.cpy
lmark -f -a src3
ut_launch -done 0 -failed 0 -frozen 1 -failed_frozen  1  -rc 1 -steady 0 lmake src3.cpy
echo 1 >src3
ut_launch -done 1 -failed 0 -frozen 1 -new_frozen     1  -rc 0 -steady 0 lmake src3.cpy
lmark -f -d src3
ut_launch -done 0 -failed 0 -frozen 0                    -rc 1 -steady 0 lmake src3.cpy
lmark -f -a src3
ut_launch -done 0 -failed 0 -frozen 1 -new_frozen     1  -rc 0 -steady 0 lmake src3.cpy
echo 2 >src3
ut_launch -done 1 -failed 0 -frozen 1 -changed_frozen 1  -rc 0 -steady 0 lmake src3.cpy
lmark -f -a src3.cpy
echo 3 >src3
ut_launch -done 1 -failed 0 -frozen 2                    -rc 0 -steady 0 lmake src3.cpy.cpy
