#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023-2025 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -done 2 -new 1 lmake src1.9.wait &
sleep 3
lmake src1.6.wait &
sleep 3
kill -2 %2 ; date
wait %2 || :
ut_launch -done 2 lmake src1.6.wait
wait %1
