#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ut_launch -dep_err 1 -done 1 -new 1 -changed 1 -dep_err 1 -rc 1 lmake src1.6r.wait &
sleep 3
echo new1 > src1
wait %1

ut_launch -done 1 -steady 0 -dep_err 0 -rc 0 lmake src1.6r.wait
