#!/bin/bash -e

# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023-2025 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

echo 1 > src1

ut_launch -done 2 -rerun 0            -new 1 -steady 0    -rc 0 lmake src1.6r.wait &
sleep 3
touch src1
wait %1
ut_launch -done 1          -changed 0                     -rc 0 lmake src1.6r.wait

echo 2 > src1

ut_launch -done 1 -rerun 0 -changed 1 -new 0 -dep_error 1 -rc 1 lmake src1.6r.wait &
sleep 3
echo >> src1
wait %1
ut_launch -done 1          -changed 0                     -rc 0 lmake src1.6r.wait

echo 3 > src1

ut_launch -done 1 -rerun 0 -changed 2 -new 0 -dep_error 1 -rc 1 lmake src1.r6.wait &
sleep 3
echo >> src1
wait %1
ut_launch -done 2          -changed 0                     -rc 0 lmake src1.r6.wait
