// This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
// Copyright (c) 2023-2025 Doliam
// This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
// This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#pragma once

#include "disk.hh"
#include "hash.hh"
#include "serialize.hh"
#include "time.hh"

#include "autodep/env.hh"

// START_OF_VERSIONING
ENUM_2( Dflag        // flags for deps
,	NRule = Required // number of Dflag's allowed in rule definition
,	NDyn  = Static   // number of Dflag's allowed in side flags
	//
,	Critical         // if modified, ignore following deps
,	Essential        // show when generating user oriented graphs
,	IgnoreError      // dont propagate error if dep is in error (Error instead of Err because name is visible from user)
,	Required         // dep must be buildable (static deps are always required)
,	Static           // is static dep, for internal use only
,	Full             // if false, dep is only necessary to compute resources
)
// END_OF_VERSIONING
static constexpr ::amap<Dflag,char,N<Dflag>> DflagChars {{
	{ Dflag::Critical    , 'c' }
,	{ Dflag::Essential   , 'E' }
,	{ Dflag::IgnoreError , 'e' }
,	{ Dflag::Required    , 'r' }
,	{ Dflag::Static      , 'S' }
,	{ Dflag::Full        , 'F' }
}} ;
using Dflags = BitMap<Dflag> ;
static_assert(chk_enum_tab(DflagChars)) ;
static constexpr Dflags DflagsDflt       = Dflag::Full                               ;
static constexpr Dflags DflagsDfltStatic = DflagsDflt|Dflag::Essential|Dflag::Static ;
static constexpr Dflags DflagsDfltDyn    = DflagsDflt                                ;
static constexpr Dflags DflagsDfltDepend = DflagsDflt|Dflag::Required                ;

// START_OF_VERSIONING
ENUM_1( ExtraDflag
,	NRule          // all flags allowed
,	Top
,	Ignore
)
// END_OF_VERSIONING
static constexpr ::amap<ExtraDflag,char,N<ExtraDflag>> ExtraDflagChars {{
	{ ExtraDflag::Top    , 0   }
,	{ ExtraDflag::Ignore , 'I' }
}} ;
using ExtraDflags = BitMap<ExtraDflag> ;
static_assert(chk_enum_tab(ExtraDflagChars)) ;

// START_OF_VERSIONING
ENUM_2( Tflag      // flags for targets
,	NRule = Static // number of Tflag's allowed in rule definition
,	NDyn  = Phony  // number of Tflag's allowed inside flags
,	Essential      // show when generating user oriented graphs
,	Incremental    // reads are allowed (before earliest write if any)
,	NoWarning      // warn if target is either uniquified or unlinked and generated by another rule
,	Phony          // accept that target is not generated
,	Static         // is static  , for internal use only, only if also a Target
,	Target         // is a target, for internal use only
)
// END_OF_VERSIONING
static constexpr ::amap<Tflag,char,N<Tflag>> TflagChars {{
	{ Tflag::Essential   , 'E' }
,	{ Tflag::Incremental , 'i' }
,	{ Tflag::NoWarning   , 'w' }
,	{ Tflag::Phony       , 'p' }
,	{ Tflag::Static      , 'S' }
,	{ Tflag::Target      , 'T' }
}} ;
using Tflags = BitMap<Tflag> ;
static_assert(chk_enum_tab(TflagChars)) ;
inline bool static_phony(Tflags tf) {
	return tf[Tflag::Target] && (tf[Tflag::Static]||tf[Tflag::Phony]) ;
}

// START_OF_VERSIONING
ENUM_1( ExtraTflag
,	NRule = Allow  // number of Tflag's allowed in rule definition
,	Top
,	Ignore
,	Optional
,	SourceOk       // ok to overwrite source files
,	Allow          // writing to this target is allowed (for use in clmake.target and ltarget)
,	Wash           // target was unlinked when washing before job execution
)
// END_OF_VERSIONING
static constexpr ::amap<ExtraTflag,char,N<ExtraTflag>> ExtraTflagChars {{
	{ ExtraTflag::Top      , 0   }
,	{ ExtraTflag::Ignore   , 'I' }
,	{ ExtraTflag::Optional , 0   }
,	{ ExtraTflag::SourceOk , 's' }
,	{ ExtraTflag::Allow    , 'a' }
,	{ ExtraTflag::Wash     , 0   }
}} ;
using ExtraTflags = BitMap<ExtraTflag> ;
static_assert(chk_enum_tab(ExtraTflagChars)) ;

// START_OF_VERSIONING
ENUM( Comment
,	None
// syscalls
,	access
,	canonicalize_file_name
,	chdir
,	chmod
,	creat                      , creat64
,	clone                      , clone3
,	dlmopen
,	dlopen
,	execv                      , execvDep
,	execve                     , execveDep   , execveat          , execveatDep
,	execvp                     , execvpDep
,	execvpe                    , execvpeDep
,	                                           faccessat         , faccessat2
,	fchdir
,	                                           fchmodat
,	fopen                      , fopen64
,	fork
,	freopen                    , freopen64
,	                                           fstatat           , fstatat64
,	                                           futimesat
,	la_objopen
,	la_objsearch
,	link                                     , linkat
,	lstat                      , lstat64
,	lutimes
,	mkdir                                    , mkdirat
,	mkostemp                   , mkostemp64
,	mkostemps                  , mkostemps64
,	mkstemp                    , mkstemp64
,	mkstemps                   , mkstemps64
,	mount
,	                                           name_to_handle_at
,	                                           newfstatat
,	oldlstat
,	oldstat
,	open                       , open64      , openat            , openat64     , openat2
,	open_tree
,	opendir
,	readlink                                 , readlinkat
,	realpath
,	rename                                   , renameat          , renameat2
,	rmdir
,	scandir                    , scandir64   , scandirat         , scandirat64
,	stat                       , stat64
,	statx
,	symlink                                  , symlinkat
,	truncate                   , truncate64
,	unlink                                   , unlinkat
,	utime
,	                                           utimensat
,	utimes
,	                                           __fxstatat        , __fxstatat64
,	                                           __lxstat          , __lxstat64
,	__open                     , __open64
,	__open_2                   , __open64_2  , __openat_2        , __openat64_2
,	__open64_nocancel
,	__open_nocancel
,	__readlink__chk                          , __readlinkat_chk
,	__realpath_chk
,	__xstat                     , __xstat64
// lmake functions
,	analyzed
,	chkDeps
,	computedCrcs
,	decode
,	depAndTarget
,	depend
,	encode
,	endJob
,	endOverhead
,	enteredNamespace
,	hot
,	kill
,	lostServer
,	panic
,	startInfo
,	startJob
,	startOverhead
,	staticDep
,	staticExec
,	staticTarget
,	staticUnlnk
,	stderr
,	stdin
,	stdout
,	stillAlive
,	timeout
,	target
,	tmp
,	trace
,	unstable
,	uploadedToCache
,	washed
)
// END_OF_VERSIONING

// START_OF_VERSIONING
ENUM( CommentExt
,	Err
,	File
,	Last
,	LdLibraryPath
,	Killed
,	Lnk
,	NoFollow
,	Orig
,	RunPath
,	Read
,	Reply
,	Stat
,	Unlnk
,	Write
)
using CommentExts = BitMap<CommentExt> ;
// END_OF_VERSIONING
