Comment(
	This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
	Copyright (c) 2023-2026 Doliam
	This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
	This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
)

Title(lautodep,mimic OpenLmake job prelude)

.SH SYNOPSIS
B_(lautodep) [I_(OPTION)]... I_(cmd) I_(args)...

.SH DESCRIPTION
.LP
B_(lautodep) is used by B_(ldebug) to launch jobs in an adequate environment.
It may also be useful when designing a flow to try various options.
It allows to see what information (deps and targets) are recorded by code instrumentation OpenLmake injects in jobs to track activity without actually run a job under its control.
.LP
The trace generated by B_(lautodep) is halfly digested in the sens that :
Bullet
Only a summary of pertinent accesses are provided, unlike C_(strace) that can generate a line for each access.
There is a line for each accessed file, which may be a read or nothing, possibly followed by a write or an unlink.
Bullet
Accesses are tracked as for OpenLmake, i.e. files outside the repo are not tracked, except read accesses in a source dir.
Bullet
When symbolic links are supported, they are resolved according to the required support level and additional deps may be generated when needed for OpenLmake to work properly.
Bullet
It is not fully digested as dep/target flags that are provided in rules are not taken into account.
A full digestion to mimic OpenLmake would require a whole lot of information that would make the user interface significantly heavier, defeating the usefulness of this tool.
.LP
Accesses are split into 2 categories :
Bullet Targets : a prefix mentions the type of target, unlink versus write, preceded by a read or not.
Bullet Deps    : a kind of ascii art render parallel accesses.

.SH OPTIONS

Item(B_(-a),B_(--auto-mkdir))
Mimic setting the rule attribute B_(auto_mkdir)=I_(True).

Item(B_(-c) I_(abs_dir),B_(--chroot-dir)=I_(abs_dir))
Mimic setting the rule attribute B_(chroot_dir)=I_(abs_dir).

Item(B_(-C) I_(actions),B_(--chroot-actions)=I_(actions))
Mimic setting the rule attribute B_(chroot_actions)=I_(actions).
I_(actions) is a comma separated list of actions.

Item(B_(-d) I_(dir),B_(--cwd)=I_(dir))
Mimic setting the rule attribute B_(cwd)=I_(dir).

Item(B_(-D),B_(--readdir-ok))
Mimic setting the rule attribute B_(readdir_ok)=I_(True).

Item(B_(-e) I_(list),B_(--env)=I_(list))
I_(list) must be provided as a  tuple or list of str using the python syntax (which most probably requires shell quoting).
Listed variables are kept from the environment.

Item(B_(-k),B_(--keep-tmp))
Dont erase tmp dir after execution.

Item(B_(-l) I_(key),B_(--link-support)=I_(key))
Mimic setting the config attribute B_(link_support)=I_(key).

Item(B_(-m) I_(key),B_(--autodep-method)=I_(key))
Mimic setting the rule attribute B_(autodep)=I_(key).

Item(B_(-M),B_(--mount-chroot-ok))
Mimic setting the rule attribute B_(mount_chroot_ok)=I_(True).

Item(B_(-o) I_(file),B_(--out)=I_(file))
Write access info (deps and targets) to I_(file).

Item(B_(-r) I_(abs_dir),B_(--lmake-root)=I_(abs_dir))
Mimic setting the rule attribute B_(lmake_root)=I_(abs_dir).

Item(B_(-s) I_(list),B_(--source-dirs)=I_(list))
I_(list) must be provided as a  tuple or list of str using the python syntax (which most probably requires shell quoting).
Mimic setting the rule attribute B_(source_dirs)=I_(list).

Item(B_(-t) I_(abs_dir),B_(--tmp-dir)=I_(abs_dir))
This option is mandatory.
Set the physical tmp dir.
The tmp dir is cleaned (i.e. all files inside it are B_(rm)'ed) before execution.
It is also cleaned after execution unless the B_(--keep-tmp) or B_(-k) is given.

Item(B_(-L) I_(abs_dir),B_(--lmake-view)=I_(abs_dir))
Mimic setting the rule attribute B_(lmake_view)=I_(abs_dir).

Item(B_(-R) I_(abs_dir),B_(--repo-view)=I_(abs_dir))
Mimic setting the rule attribute B_(repo_view)=I_(abs_dir).

Item(B_(-T) I_(abs_dir),B_(--tmp-view)=I_(abs_dir))
Mimic setting the rule attribute B_(tmp_view)=I_(abs_dir).

Item(B_(-V) I_(dict),B_(--views)=I_(dict))
I_(dict) must be provided as a dict mapping str to view descriptions using the python syntax (which most probably requires shell quoting).
Mimic setting the rule attribute B_(views)=I_(dict).

.SH "EXIT STATUS"
.LP
B_(lautodep) exits with a status of zero if the command was executed with no error.
Else it exits with a non-zero status:
.LP
Item(B_(1))  command did not exit without error
Item(B_(2))  internal error, should not occur
Item(B_(5))  internal repo state was inconsistent
Item(B_(7))  adequate permissions were missing, typically write access
Item(B_(10)) some syscall failed
Item(B_(11)) bad usage : command line options and arguments coul not be parsed
Item(B_(12)) bad repo version, repo need to be cleaned, e.g. with B_(git clean -ffdx)

.SH EXAMPLES

A typical call could be:
.LP
V_(lautodep -e"['DISPLAY','LMAKE_HOME','HOME','PATH',]" -k -lfull -mld_audit -oaccesses -t/my_tmp/$$ -- /bin/bash cmd)

.SH FILES
CommonFiles

Footer
