Comment(
	This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
	Copyright (c) 2023-2026 Doliam
	This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
	This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
)

Header(lcheck_deps,ensure deps collected so far in a OpenLmake job are up-to-date)

.SH DESCRIPTION
.LP
B_(lcheck_deps) ensures that all deps accessed so far are up-to-date.
It also ensures that no pre-existing targets have been seen so far.
If this is not the case, the job is killed, generating a rerun report, the deps are rebuilt (and the necessary targets are unlinked) and the job is rerun.
.LP
This is useful before starting a heavy computation. Typically, deps are computed and accessed before the heavy sequence and calling B_(check_deps) allows to avoid
running a heavy computation with bad inputs. It is not a semantic problem as OpenLmake will realize the situation, rebuild the deps and rerun the job, but it may be a performance problem.
.LP
Imagine for exemple that you have to compile I_(heavy.c) that includes a file I_(generated.h) generated by the command I_(generator).
Imagine then that you type B_(lmake generated.h), you look at it, find that the file is syntactically correct but contains a bug.
You then modify I_(generator) and because you are confident in your modification, you type B_(lmake heavy.o).
.LP
OpenLMake will run the compilation of I_(heavy.o), which lasts 10 minutes and discover that you need I_(generated.h), which is out-of-date.
It will then rebuild I_(generated.h) and rerun the compilation to I_(heavy.o), another 10 minutes.
.LP
Suppose now that your compilation script separates the preprocessor (say 10 secondes) phase from the compilation (10 minutes) phase and call B_(lcheck_deps) inbetween.
In that case, the first run will stop after preprocessing as B_(lcheck_deps) will kill the job at that moment and the overall time will be 10 minutes 10 secondes instead of 20 minutes.
.LP
Note that to be imunised against pre-existing targets (only pertinent for star-targets), such targets must be written before B_(lcheck_deps) is called.

.SH OPTIONS
.LP
Item(B_(-d) I_(delay),B_(--delay)=I_(delay)) delay check by I_(delay) seconds.
Unless B_(--sync) is also specified, this command returns immediately, though (cf. NOTES).
.LP
Item(B_(-s),B_(--sync)) wait for server answer rather than letting job go speculatively while it is interrogated.
return code will be 1 if at least one dep is in error.
This is necessary, even without checking return code, to ensure that after this call, the dirs of previous deps actually exist if such deps are not read (such as with B_(lmake.depend)) (cf. CAVEAT).

.SH "EXIT STATUS"
.LP
B_(lcheck_deps) exits with a status of zero if deps were up-to-date and no pre-existing targets have been seen so far.
Else it exits with a non-zero status:
.LP
Item(B_(1))  some deps were not up-to-date or a pre-existing target has been seen so far
Item(B_(2))  internal error, should not occur
Item(B_(11)) bad usage : command line options and arguments coul not be parsed

.SH EXAMPLES
.LP
V_(lcheck_deps)

.SH CAVEAT
.LP
If used in conjonction with the B_(kill_sigs) attribute with a handler to manage the listed signal(s) (typically using B_(trap ... SIG) and without the B_(--sync) option,
it may be that the command following the call to B_(lcheck_deps) does not see the signal.
This is due to a race condition in I_(bash) when command is just starting.
.LP
This may be annoying if said command was supposed to do some clean up or if it is very long.
The solution in this case is to pass the B_(--sync) option to B_(lcheck_deps).
This has a small cost in the general case where deps are actually up-to-date, but provides a reliable way to kill the job as B_(lcheck_deps) will still be running when signal fires up.

.SH NOTES
.LP
This is a (performance) problem only during the first run of I_(heavy.o).
On subsequent runs, in particular during a typical edit-compile-debug loop, OpenLmake will know the deps and will launch jobs in the proper order.
But during the first run, it has no knowledge that I_(heavy.c) actually includes I_(generated.h).
.LP
Most often, when I_(generated.h) is out-of-date, it is syntactically incorrect (for example it does not exist),
so the first run fails quite early (without spending its heavy optimization time).
.LP
In the case where I_(generated.h) is rebuilt identically to its previous content, there will be no second run without B_(lcheck_deps) call,
so B_(lcheck_deps) has a (minor) adverse effect leading to an overall time of 10 minutes 10 seconds instead of 10 minutes.
.LP
Despite these remarks, there are case where B_(lcheck_deps) is very welcome.
.LP
The I_(delay) option is useful in situations such as compilation where all input files are read upfront before spending time doing the actual job.
Because there is no way to insert a call to this command after having read the files but before carrying out compilation, an alternative consists in executing it with a delay upfront.
If I_(delay) is long enough for all files to be read but substantially smaller than the compilation time,
time can be save by avoiding full compilation with bad inputs when deps are being discovered.

Footer
