Comment(
	This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
	Copyright (c) 2023-2025 Doliam
	This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
	This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
)

Header(lcollect,remove obsolete files and dirs)

.SH DESCRIPTION
.LP
While OpenLmake is used and the repo evolves, new files are generated and some files become obsolete.
But these obsolete files are not removed from disk and after a while, this may occupy a substantial disk space.
B(lcollect) can be used to remove all such files.

.LP
B(lcollect) works by walking through the dirs and files passed as argument and decide for each of them whether to keep, quarantine or remove them.

.LP
Files ignored as specified in B(lmake.config.collect) are kept, though.
This is particularly useful if files are generated with the B(ignore) flag, in which case OpenLmake does not see they have been generated
and B(lcollect) would consider them as foreign files to be quarantined.

.LP
B(lcollect) is harmless: only files generated by OpenLmake are removed.
If a file is determined as useless but it is not sure that it was generated by an old job, it is quarantined (i.e. it is moved to the I(LMAKE/quarantine) dir) instead of being removed.
It is is then easy to execute B(rm -rf LMAKE/quarantine) if such a backup is not desirable.

ClientGeneralities()

ClientOptions(,color)

SpecificOptions
Item(B(-n),B(--dry-run)) report only, dont actually execute actions.

.SH FILES
CommonFiles

.SH NOTES
.LP
B(lcollect) does not prune OpenLmake internal book-keeping data.
Use C(lrepair,1) for that.

Footer
