Comment(
	This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
	Copyright (c) 2023-2026 Doliam
	This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
	This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
)

Header(lcollect,remove obsolete files and dirs)

.SH DESCRIPTION
.LP
While OpenLmake is used and the repo evolves, new files are generated and some files become obsolete.
But these obsolete files are not removed from disk and after a while, this may occupy a substantial disk space.
B_(lcollect) can be used to remove all such files.

.LP
B_(lcollect) works by walking through the dirs and files passed as argument and decide for each of them whether to keep, quarantine or remove them.

.LP
Files ignored as specified in B_(lmake.config.collect) are kept, though.
This is particularly useful if files are generated with the B_(ignore) flag, in which case OpenLmake does not see they have been generated
and B_(lcollect) would consider them as foreign files to be quarantined.

.LP
B_(lcollect) is harmless: only files generated by OpenLmake are removed.
If a file is determined as useless but it is not sure that it was generated by an old job, it is quarantined (i.e. it is moved to the I_(LMAKE/quarantine) dir) instead of being removed.
It is is then easy to execute B_(rm -rf LMAKE/quarantine) if such a backup is not desirable.

ClientGeneralities()

ClientOptions(,color)

SpecificOptions
Item(B_(-n),B_(--dry-run)) report only, dont actually execute actions.

.SH "EXIT STATUS"
.LP
B_(lcollect) exits with a status of zero if the whole process went out smoothly.
Else it exits with a non-zero status:
.LP
Item(B_(2))  internal error, should not occur
Item(B_(3))  I_(Lmakefile.py) could not be read or contained an error
Item(B_(4))  server could not be started
Item(B_(5))  internal repo state was inconsistent
Item(B_(6))  repo need to be cleaned, e.g. with B_(git clean -ffdx)
Item(B_(7))  adequate permissions were missing, typically write access
Item(B_(8))  server crashed, should not occur
Item(B_(9))  repo need to be steady (no on-going lmake running)
Item(B_(10)) some syscall failed
Item(B_(11)) bad usage : command line options and arguments coul not be parsed
Item(B_(12)) bad repo version, repo need to be cleaned, e.g. with B_(git clean -ffdx)

.SH EXAMPLES
.LP
V_(lcollect)

.SH FILES
CommonFiles

.SH NOTES
.LP
B_(lcollect) does not prune OpenLmake internal book-keeping data.
Use C_(lmake_repair,1) for that.

Footer
