#!/bin/bash
# This file is part of the open-lmake distribution (git@github.com:cesar-douady/open-lmake.git)
# Copyright (c) 2023-2025 Doliam
# This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

case $(g++ --version | awk 'NR==1 {print $NF}') in
	13*) ;;
	14*) ;;
	*  ) echo gcc version is neither version 13 nor 14 >skipped ; exit 0 ;;
esac

lmake use.o
